# Generated by Django 3.0.4 on 2020-11-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=200)),
                ('add_date', models.DateTimeField(verbose_name='date added')),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
    ]
