# Generated by Django 3.0.4 on 2020-11-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtype',
            name='opened',
            field=models.BooleanField(default=False),
        ),
    ]
