# Generated by Django 3.0.4 on 2020-11-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_auto_20201103_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='exp_date',
            field=models.DateField(blank=True, null=True, verbose_name='expire date'),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='opened_date',
            field=models.DateField(blank=True, null=True, verbose_name='opened date'),
        ),
    ]
