# Generated by Django 3.0.4 on 2020-11-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_auto_20201103_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtype',
            name='exp_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='expire date'),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='opened_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='opened date'),
        ),
    ]
